package com.hd.hd_backend.utils;

public enum Code {
    REGISTER_SUCCESS,
    REGISTER_FAIL,

    LOGIN_SUCCESS,
    LOGIN_FAIL,

    FOOD_LIST_SUCCESS,
    FOOD_LIST_FAIL,

    FOOD_RECORD_ADD_SUCCESS,
    FOOD_RECORD_ADD_FAIL,

    FOOD_RECORD_GET_SUCCESS,
    FOOD_RECORD_GET_FAIL,

    FOOD_ITEM_GET_SUCCESS,
    FOOD_ITEM_GET_FAIL,

    EXERCISE_RECORD_GET_SUCCESS,
    EXERCISE_RECORD_GET_FAIL,

    EXERCISE_RECORD_ADD_SUCCESS,
    EXERCISE_RECORD_ADD_FAIL,

    EXERCISE_LIST_SUCCESS,
    EXERCISE_LIST_FAIL,

    EXERCISE_ITEM_ADD_SUCCESS,
    EXERCISE_ITEM_ADD_FAIL,

    UPDATE_USER_SUCCESS,
    UPDATE_USER_FAIL,

    FOOD_RECORD_UPDATE_SUCCESS,
    FOOD_RECORD_UPDATE_FAIL,

    FOOD_RECORD_DELETE_SUCCESS,
    FOOD_RECORD_DELETE_FAIL,

    FOOD_ITEM_UPDATE_SUCCESS,
    FOOD_ITEM_UPDATE_FAIL,

    FOOD_ITEM_ADD_SUCCESS,
    FOOD_ITEM_ADD_FAIL,

    FOOD_ITEM_DELETE_SUCCESS,
    FOOD_ITEM_DELETE_FAIL,

}
