package com.hd.hd_backend.utils;

public enum WebSocketCode {
    REGISTER_SUCCESS,
    REGISTER_FAIL,

    LOGIN_SUCCESS,
    LOGIN_FAIL,

    FOOD_LIST_SUCCESS,
    FOOD_LIST_FAIL,

    FOOD_RECORD_ADD_SUCCESS,
    FOOD_RECORD_ADD_FAIL,

    FOOD_RECORD_GET_SUCCESS,
    FOOD_RECORD_GET_FAIL,

    FOOD_ITEM_GET_SUCCESS,
    FOOD_ITEM_GET_FAIL,

    EXERCISE_RECORD_GET_SUCCESS,
    EXERCISE_RECORD_GET_FAIL,

    EXERCISE_RECORD_ADD_SUCCESS,
    EXERCISE_RECORD_ADD_FAIL,

    EXERCISE_LIST_SUCCESS,
    EXERCISE_LIST_FAIL,

    EXERCISE_ITEM_ADD_SUCCESS,
    EXERCISE_ITEM_ADD_FAIL,

    UPDATE_USER_SUCCESS,
    UPDATE_USER_FAIL,

    FOOD_RECORD_UPDATE_SUCCESS,
    FOOD_RECORD_UPDATE_FAIL,

    FOOD_RECORD_DELETE_SUCCESS,
    FOOD_RECORD_DELETE_FAIL,

    FOOD_ITEM_UPDATE_SUCCESS,
    FOOD_ITEM_UPDATE_FAIL,

    FOOD_ITEM_ADD_SUCCESS,
    FOOD_ITEM_ADD_FAIL,

    FOOD_ITEM_DELETE_SUCCESS,
    FOOD_ITEM_DELETE_FAIL,

    EXERCISE_RECORD_DELETE_SUCCESS,
    EXERCISE_RECORD_DELETE_FAIL,

    POST_CREATE_SUCCESS,
    POST_CREATE_FAIL,
    POST_DELETE_SUCCESS,
    POST_DELETE_FAIL,
    POST_UPDATE_SUCCESS,
    POST_UPDATE_FAIL,
    POST_GET_SUCCESS,
    POST_GET_FAIL,

    COMMENT_CREATE_SUCCESS,
    COMMENT_CREATE_FAIL,
    COMMENT_DELETE_SUCCESS,
    COMMENT_DELETE_FAIL,
    COMMENT_UPDATE_SUCCESS,
    COMMENT_UPDATE_FAIL,
    COMMENT_GET_SUCCESS,
    COMMENT_GET_FAIL,

    WEIGHT_ADD_SUCCESS,
    WEIGHT_ADD_FAIL,
    WEIGHT_DELETE_SUCCESS,
    WEIGHT_DELETE_FAIL,
    WEIGHT_UPDATE_SUCCESS,
    WEIGHT_UPDATE_FAIL,
    WEIGHT_GET_SUCCESS,
    WEIGHT_GET_FAIL,
    WEIGHT_LATEST_GET_SUCCESS,
    WEIGHT_LATEST_GET_FAIL
}
